### PR TITLE
Update vulnerable dependencies

### PR DESCRIPTION
**Pull request by rootd00d**
* Updates all vulnerable dependencies
* Update package.json version to 0.0.4

### CODE REVIEW

**Review by rootd00d — COMMENTED** [review]
Would love to get this package updated ASAP, @cgadam @wbeard @brgaulin @vieron

**Comment by rootd00d** [comment]
#15

**Comment by cgadam** [comment]
Thansk!! @rootd00d

**Comment by cgadam** [comment]
@rootd00d `0.0.4` is now published to `npm`. Let me know how that works! Have a good one!
https://www.npmjs.com/package/artifactory-api/v/0.0.4

**Pull request merged**
